# Solver Configuration File

# Parameters controlling the solver's core logic and termination criteria
solver_params:
  # The relative gap at which the solver will terminate
  optimality_gap: 0.0001
  # The maximum time in seconds the solver is allowed to run
  time_limit_seconds: 300

# Parameters controlling the strategic decisions of the solver
strategy:
  # Method for selecting the next node to explore from the active nodes list.
  # Options: 'best_bound', 'depth_first', 'hybrid'
  node_selection: 'depth_first'
  
  # Method for selecting the variable to branch on.
  # Options: 'most_fractional', 'strong_branching'
  branching_variable: 'most_fractional'

